[workspace]
members = [
    "client",
    "lib/formats",
    "lib/renderer",
    "lib/game",
    "lib/network",
    "lib/ui-core",
    "lib/ui-component",
    "lib/audio",
    "tools",
    "tools/grf-editor",
    "tools/effect-viewer-hot",
    "tools/rendering-viewer-hot",
    "tools/rsw-viewer-hot",
    "lib/ui-component-hot",
]
resolver = "2"

[workspace.dependencies]
# Needed by server's models crate (workspace = true)

tracing = "0.1.41"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter"] }
# Needed by server's packets crate (workspace = true)
byteorder = "1.5.0"
json-flat-parser = "0.1.0"
flate2 = "1.1"
encoding_rs = "0.8"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

wgpu = "28"
winit = "0.30"
glam = "0.32"
bytemuck = { version = "1.25", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "tga", "bmp"] }
ab_glyph = "0.2"
eframe = "0.33.3"
rfd = "0.15"
tokio = { version = "1", features = ["net", "rt", "sync", "macros", "io-util", "time"] }

# Server crate git dependencies
models = { git = "https://github.com/nmeylan/rust-ro.git", rev = "0362dc12" }
movement = { git = "https://github.com/nmeylan/rust-ro.git", rev = "0362dc12" }
packets = { git = "https://github.com/nmeylan/rust-ro.git", rev = "0362dc12" }

# Internal crates
ragnarok-formats = { path = "lib/formats" }
ragnarok-renderer = { path = "lib/renderer" }
ragnarok-game = { path = "lib/game" }
ragnarok-network = { path = "lib/network" }
ragnarok-ui = { path = "lib/ui-core" }
ragnarok-ui-component = { path = "lib/ui-component" }
ragnarok-audio = { path = "lib/audio" }
libloading = "0.8"
