[package]
name = "effect-viewer-hot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ragnarok-formats = { workspace = true }
ragnarok-renderer = { workspace = true }
ragnarok-game = { workspace = true }
ragnarok-ui = { workspace = true }
models = { workspace = true }
