[package]
name = "ragnarok-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
ragnarok-formats = { workspace = true }
ragnarok-game = { workspace = true }
models = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
winit = { workspace = true }
ab_glyph = { workspace = true }
