[package]
name = "ragnarok-tools"
version = "0.1.0"
edition = "2024"

[lib]
name = "ragnarok_tools"
path = "src/lib.rs"

[[bin]]
name = "sprite-viewer"
path = "src/bin/sprite_viewer.rs"

[[bin]]
name = "rendering-viewer"
path = "src/bin/rendering_viewer.rs"

[[bin]]
name = "rsw-viewer"
path = "src/bin/rsw_viewer.rs"

[[bin]]
name = "effect-viewer"
path = "src/bin/effect_viewer.rs"

[[bin]]
name = "dump-rsw-lights"
path = "src/bin/dump_rsw_lights.rs"


[dependencies]
ragnarok-formats = { workspace = true }
ragnarok-renderer = { workspace = true }
ragnarok-game = { workspace = true }
ragnarok-ui = { workspace = true }
models = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
notify = "7"
libloading = { workspace = true }
arboard = { version = "3", features = ["wayland-data-control"] }
gif = "0.13"
